
package interfazgrafica;

import javax.swing.JOptionPane;

/**
 *
 * @author El capo
 */
public class Calculaora extends javax.swing.JFrame {
    int a, b, suma, resta, multi;
    float divi;
    /**
     * Creates new form Calculaora
     */
    public Calculaora() {
        initComponents();
        this.setLocationRelativeTo(null);
        TextField_resultado.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_numero1 = new javax.swing.JLabel();
        TextField_numero1 = new javax.swing.JTextField();
        Label_numero2 = new javax.swing.JLabel();
        TextField_numero2 = new javax.swing.JTextField();
        Button_suma = new javax.swing.JButton();
        Button_resta = new javax.swing.JButton();
        Button_mult = new javax.swing.JButton();
        Button_divi = new javax.swing.JButton();
        Label_resultado = new javax.swing.JLabel();
        TextField_resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_numero1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_numero1.setText("Numero 1:");

        TextField_numero1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Label_numero2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_numero2.setText("Numero 2:");

        TextField_numero2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Button_suma.setBackground(new java.awt.Color(204, 255, 255));
        Button_suma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Button_suma.setText("Suma");
        Button_suma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_sumaActionPerformed(evt);
            }
        });

        Button_resta.setBackground(new java.awt.Color(204, 255, 255));
        Button_resta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Button_resta.setText("Resta");
        Button_resta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_restaActionPerformed(evt);
            }
        });

        Button_mult.setBackground(new java.awt.Color(204, 255, 255));
        Button_mult.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Button_mult.setText("Multiplicación");
        Button_mult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_multActionPerformed(evt);
            }
        });

        Button_divi.setBackground(new java.awt.Color(204, 255, 255));
        Button_divi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Button_divi.setText("División");
        Button_divi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_divi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_diviActionPerformed(evt);
            }
        });

        Label_resultado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_resultado.setText("Resultado:");

        TextField_resultado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TextField_resultado.setActionCommand("<Not Set>");
        TextField_resultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextField_resultado.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_resultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_suma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_resta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_mult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_divi))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Label_numero2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextField_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Label_numero1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextField_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_numero1)
                    .addComponent(TextField_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_numero2)
                    .addComponent(TextField_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_suma)
                    .addComponent(Button_resta)
                    .addComponent(Button_mult)
                    .addComponent(Button_divi))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_resultado)
                    .addComponent(TextField_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_multActionPerformed
        // TODO add your handling code here:
        if (TextField_numero1.getText().equals("") || TextField_numero2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "intente de nuevo","Error" ,JOptionPane.ERROR_MESSAGE);
            TextField_numero1.setText("");
            TextField_numero2.setText("");
            TextField_numero1.requestFocus();
        }else{
        a = Integer.parseInt(TextField_numero1.getText());
        b = Integer.parseInt(TextField_numero2.getText());
        multi = a * b;
        TextField_resultado.setText(""+multi);
            
        }
    }//GEN-LAST:event_Button_multActionPerformed

    private void Button_diviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_diviActionPerformed
        // TODO add your handling code here:
        if (TextField_numero1.getText().equals("") || TextField_numero2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "intente de nuevo","Error" ,JOptionPane.ERROR_MESSAGE);
            TextField_numero1.setText("");
            TextField_numero2.setText("");
            TextField_numero1.requestFocus();
        }else{
            
        a = Integer.parseInt(TextField_numero1.getText());
        b = Integer.parseInt(TextField_numero2.getText());
        divi = (float) ((double) a / b);
        TextField_resultado.setText(""+divi);
        }
    }//GEN-LAST:event_Button_diviActionPerformed

    private void Button_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_sumaActionPerformed
        // TODO add your handling code here:
        if (TextField_numero1.getText().equals("") || TextField_numero2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "intente de nuevo","Error", JOptionPane.ERROR_MESSAGE);
            TextField_numero1.setText("");
            TextField_numero2.setText("");
            TextField_numero1.requestFocus();
        }else{
        a = Integer.parseInt(TextField_numero1.getText());
        b = Integer.parseInt(TextField_numero2.getText());
        suma = a + b;
        TextField_resultado.setText(""+suma);
            
        }
    }//GEN-LAST:event_Button_sumaActionPerformed

    private void Button_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_restaActionPerformed
        // TODO add your handling code here:
        if (TextField_numero1.getText().equals("") || TextField_numero2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "intente de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
            TextField_numero1.setText("");
            TextField_numero2.setText("");
            TextField_numero1.requestFocus();
        }else{
        a = Integer.parseInt(TextField_numero1.getText());
        b = Integer.parseInt(TextField_numero2.getText());
        resta = a - b;
        TextField_resultado.setText(""+resta);
            
        }
    }//GEN-LAST:event_Button_restaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculaora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculaora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculaora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculaora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculaora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_divi;
    private javax.swing.JButton Button_mult;
    private javax.swing.JButton Button_resta;
    private javax.swing.JButton Button_suma;
    private javax.swing.JLabel Label_numero1;
    private javax.swing.JLabel Label_numero2;
    private javax.swing.JLabel Label_resultado;
    private javax.swing.JTextField TextField_numero1;
    private javax.swing.JTextField TextField_numero2;
    private javax.swing.JTextField TextField_resultado;
    // End of variables declaration//GEN-END:variables
}
